name = "fiat-busqueda"
main = "search-worker.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "fiat-busqueda"
database_id = "20e884ca-4318-4e9b-8746-f61ef96bb93a"
